### ISSUE TITLE
Could not generate the report: HTTP 403

### ISSUE THREAD

**Issue by maksim-paskal** [allure-framework/allure-maven#157]
Got exception while `mvn allure:report`
```
[ERROR] Failed to execute goal io.qameta.allure:allure-maven:2.9:report (default-cli) on project autotest: An error has occurred in Allure report generation.: Could not generate the report: Can't install allure: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.zip
```

**To Reproduce**
_pom.xml_
```xml
...
<build>
  <plugin>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-maven</artifactId>
    <version>2.9</version>
    <configuration>
      <reportVersion>2.7.0</reportVersion>
    </configuration>
  </plugin>
</plugins>
</build>
...
```
execute generation
```bash
mvn allure:report
```

**Expected behavior**
Alure report successfully generated in ./target/site/allure-maven-plugin

**Environment**
- Using docker image `maven:3.6.1-jdk-8`
- Docker 19.3.13
- Linux (5.4.95-42.163.amzn2.x86_64)

**Comment by baev** [comment]
That was bintray rate-limit issue, should be fixed by now. See https://github.com/allure-framework/allure2/issues/832 for context.

Since 2.8.0 Allure uploaded to Maven Central instead of Bintray. Due to Bintray shutdown soon (it is reached EOL by now) I highly recommend you upgrade to latest report versions

**Comment by ntatarinov** [comment]
123
