### ISSUE TITLE
Missing API test execution data

### ISSUE THREAD

**Issue by raialmeida** [allure-framework/allure-maven#294]
**Describe the bug**

When generating the allure report through maven, I can't see the API test execution data, I'm using restAssured. Could it be a version problem with a dependency? 

**To Reproduce**
1. mvn clean test
2. mvn allure:serve

**Expected behavior**
Should display data from Headers, response in Test body

<img width="282" alt="image" src="https://github.com/allure-framework/allure-maven/assets/55969097/b5360c4d-a079-4a05-a0fd-dbd8b038cd9c">

**Screenshots**
Example of the problem

<img width="472" alt="image" src="https://github.com/allure-framework/allure-maven/assets/55969097/2c57bbb2-b12a-4863-b6d0-b095b57cef9a">

**Desktop (please complete the following information):**
 - OS: Windows
 - jdk-21

**Dependency version**

------------------------------------------
<artifactId>allure-maven</artifactId>
<version>2.12.0</version>
------------------------------------------
<artifactId>allure-junit5</artifactId>
<version>2.24.0</version>
---------------------------------------
<artifactId>rest-assured</artifactId>
<version>5.3.2</version>
---------------------------------------
<artifactId>maven-compiler-plugin</artifactId>
<version>3.11.0</version>
--------------------------------------
<artifactId>maven-surefire-plugin</artifactId>
<version>3.2.1</version>
-------------------------------------

**Comment by baev** [comment]
Sorry for the delay. It's definitely not a problem with the Allure Maven plugin; it's probably a configuration issue. If the problem is still relevant, please create a discussion here: https://github.com/orgs/allure-framework/discussions/categories/questions-support and provide as many details as possible, e.g., the sample project to reproduce the problem. We'll be happy to help!
