### ISSUE TITLE
Not able too generate Allure report due to [WARNING] Results directory for module allure-maven not found.

### ISSUE THREAD

**Issue by hyfzur** [allure-framework/allure-maven#33]
[pom.txt](https://github.com/allure-framework/allure-maven/files/862481/pom.txt)

When running the command -  mvn clean test site, the reports is not generated.

Here is the execution log - [execution-log.txt](https://github.com/allure-framework/allure-maven/files/862496/execution-log.txt)

Here is the full execution stacktrace - [log.txt](https://github.com/allure-framework/allure-maven/files/862514/log.txt)

**Comment by baev** [comment]
@HifzurRahman hi

BTW what is the point of spamming your problems everywhere? We all can see your messages in gitter

**Comment by HifzurRahman** [comment]
Hi @baev ,

Im very sorry if you think that this is spamming. I am following this [pom](https://github.com/allure-examples/allure-testng-example/blob/master/pom.xml) for testng and I am unable to generate the report. 

Yes I have shared this on Gitter too, however I think it would be more useful if there is an issue with correct resolution, so that anyone having similar problem could take help from this in the future.

**Comment by eroshenkoam** [comment]
```
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ allure-maven ---
```

Seems like maven didn't run any test.

**Comment by hyfzur** [comment]
maven is generating result. I dont know what was wrong. The reports got generated half an hour ago.
